image: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: 8
      rust_version: nightly
      target: x86_64-pc-windows-msvc

platform:
  - x64

version: '{build}'

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %rust_version% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - appveyor DownloadFile https://releases.llvm.org/5.0.0/LLVM-5.0.0-win64.exe -FileName llvm-install.exe
  - start /wait llvm-install.exe /S /D=C:\"Program Files\LLVM"
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - set RUST_BACKTRACE=1

build: off

test_script:
  - node --version
  - npm --version
  - rustc --version
  - npm install
  - cargo test
  - npm test
