language: rust

rust: nightly

env:
  - NODEJS_VERSION=8

os:
  - linux
# - osx

cache:
  - cargo: true
  - directories:
    - target
    - ~/.cargo/bin

install:
  - nvm install $NODEJS_VERSION
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cargo install clippy
    fi
  - npm install

script:
  - cargo test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      (cd crates/mhp && cargo clippy)
      (cd crates/mhp-node && cargo clippy)
      (cd crates/mhp-napi && cargo clippy)
    fi
  - npm run -s test-ci
