language: rust

rust: nightly

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - NODEJS_VERSION=8

os:
  - linux
# - osx

cache: cargo

install:
  - nvm install $NODEJS_VERSION
  - npm install

script:
  - cargo test
  - ./scripts/lint-clippy-ci.sh
  - npm test
