language: rust

matrix:
  include:
    - os: linux
      rust: stable
      env: NODEJS_VERSION=8

    - os: linux
      rust: nightly
      env: NODEJS_VERSION=8

#    - os: osx
#      rust: stable
#      env: NODEJS_VERSION=8

dist: trusty
sudo: false
osx_image: xcode8.3

install:
  - nvm install $NODEJS_VERSION
  - npm install

script:
  - cargo test
  - npm run -s test-ci
