[package]
authors = ["Alexey Orlenko <eaglexrlnk@gmail.com>"]
name = "mhp"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
futures = "0.1.16"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
